# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-Test

  target 'MVVM-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM-TestUITests' do
    # Pods for testing
  end

	pod 'Moya', '~> 14.0'

end
